### PR TITLE
hide splash screen on some android platforms

### PR DESCRIPTION
**Pull request by ElenaDiachenko**
## Description

- App is installed on simulator/device but only splash screen is displayed on app harness <= rnv picks up the index.ts file, which has no logic to hide the splash screen.

## Related issues

- https://github.com/flexn-io/renative/issues/1511

## Npm releases

n/a

### CODE REVIEW

**Review by mihaiblaga89 — APPROVED** [review]

**Review by GabrieleKaceviciute — APPROVED** [review]

**Review by pavjacko — CHANGES_REQUESTED** [review]
@ElenaDiachenko can you move `"supportedPlatforms": ["android", "ios"]` under default pluginTemplkates

**Comment by pauliusguzas** [comment]
Note from testing: android, androidtv tested and works, ios, tvos on sims no splash screen, need to test on devices

**Comment by GabrieleKaceviciute** [comment]
no splash screen on ios device (iPhone 7 Plus, OS v.15.8.1)

https://github.com/flexn-io/renative/assets/106537292/8f9de61a-8f64-4814-af63-ef8783c2c86a

**Review by GabrieleKaceviciute — CHANGES_REQUESTED** [review]
no splash screen on ios device (iPhone 7 Plus, OS v.15.8.1)

https://github.com/flexn-io/renative/assets/106537292/8f9de61a-8f64-4814-af63-ef8783c2c86a

**Comment by pauliusguzas** [comment]
Splash screen is working on my personal iphone on both rc16 and this branch, so something must be wrong with that other iphone, will create a seperate ticket

**Pull request merged**
