### PR TITLE
fix/defaultTargets_updating

### PR DESCRIPTION
**Pull request by ElenaDiachenko**
## Description

- On Android, AndroidTV, fireTV, AndroidWear, Tizen, Tizenwatch platforms defaultTarget object of .rnv/renative.json isn't updated with default platforms

## Related issues

- https://github.com/flexn-io/renative/issues/1778

## Npm releases

n/a

### CODE REVIEW

**Review by Marius456 — APPROVED** [review]

**Comment by GabrieleKaceviciute** [comment]
On android platforms (android, androidTV, androidwear, firetv) rnv asks ->
```
? What target would you like to use? Television_1080p_API_31 | TV 📺  | arch: arm64-v8a | udid: unknown
? Your default target for platform firetv is not defined. Do you want to set it to Television_1080p_API_31  Yes
```

On ios and tvos ->
```
? No global or project default simulator or device defined. Please select a supported simulator to use iPhone 16 | Phone 📱 | v: 1
8.1 (22B81) | udid: CCD32DDF-CC9D-44C8-8E4A-0CA1CD4623A7
warn: ○ run: Your default target for platform ios is set to undefined.
? What to do next? (Use arrow keys)
❯ Update project default target for platform ios
  Update global default target for platform ios
  Don't update
```

Is it expected that android target is set on global but ios you could choose?

**Comment by pauliusguzas** [comment]
tizen, tizenwatch isn't installed when user chooses any answer. And also same as on android, no way to choose where to set default target
![Uploading Screenshot 2024-11-12 at 11.59.40.png…](
Screenshot 2024-11-12 at 11 58 03

**Comment by pauliusguzas** [comment]
on mac both tizen and tizenwatch work as expected

**Comment by GabrieleKaceviciute** [comment]
windows
- Tizen -> fails the first time after `yarn bootstrap` ( doesn't matter what I choose (update global / update project / don't update)) -> tizen simulator opens, but app doesn't installed, and simulator closes when this error occurs on CLI

```
? which emulator or device would you like to launch? T-8.0-x86_64
warn: ○ run: Your default target for platform tizen is not defined.
? What to do next? Update project default target for platform tizen
√ Executing: "C:\tizen-studio\tools\sdb.exe" devices
√ Executing: C:\tizen-studio\tools\emulator\bin\em-cli.bat launch --name T-8.0-x86_64
√ Waiting for emulator to boot...
√ Executing: "C:\tizen-studio\tools\ide\bin\tizen.bat" build-web -- "C:\Users\dev\Desktop\qa\renative\packages\template-starter\platformBuilds\template_tizen" -out "C:\Users\dev\Desktop\qa\renative\packages\template-starter\platformBuilds\template_tizen\intermediate"
√ Executing: "C:\tizen-studio\tools\ide\bin\tizen.bat" package -- "C:\Users\dev\Desktop\qa\renative\packages\template-starter\platformBuilds\template_tizen\intermediate" -s RNVanillaCert -t wgt -o "C:\Users\dev\Desktop\qa\renative\packages\template-starter\platformBuilds\template_tizen\output"
√ Executing: "C:\tizen-studio\tools\ide\bin\tizen.bat" uninstall -p NkVRhWHJSX.RNVanillaTV -t T-8.0-x86_64
√ Executing: "C:\tizen-studio\tools\ide\bin\tizen.bat" install -- "C:\Users\dev\Desktop\qa\renative\packages\template-starter\platformBuilds\template_tizen\output" -n RNVanillaTV.wgt -t T-8.0-x86_64
× FAILED: "C:\tizen-studio\tools\ide\bin\tizen.bat" run -p NkVRhWHJSX -t T-8.0-x86_64
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
No emulator -t target name specified!
No emulator -t target name specified!
PS C:\Users\dev\Desktop\qa\renative\packages\template-starter>
```

NOTE - project/global default target updates correctly

**Comment by pauliusguzas** [comment]
Not implemented on kaios

**Comment by pauliusguzas** [comment]
tizen, tizenwatch, webos works without issues. Kaios never asks to choose default target (I currently have only one kaios sim, so maybe there is connection?). Also kaios sim is searched on weird path, see picture, there is "false" directory added
image

**Review by pauliusguzas — APPROVED** [review]

**Pull request merged**
