### PR TITLE
Tizen target list

### PR DESCRIPTION
**Pull request by justinasRm**
## Description

Made npx rnv run -p tizen/tizenmobile/tizenwatch show different emulators

## Related issues

- https://github.com/flexn-io/renative/issues/1152 

## Npm releases

n/a

### CODE REVIEW

**Review by Marius456 — APPROVED** [review]

**Review by GabrieleKaceviciute — DISMISSED** [review]
doesn't show any targets on windows 10 PRO Version 22H2
```
C:\Users\dev\Desktop\renative\packages\template-starter>npx rnv target list -p tizen

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ $ rnv target list -p tizen                                      │
└─────────────────────────────────────────────────────────────────┘
info: Current platform: tizen
info: Current engine: @rnv/engine-rn-web (C:\Users\dev\Desktop\renative\packages\template-starter\node_modules\@rnv\engine-rn-web)
task: ○ target list ↺1
task: ○ workspace configure ↺1
task: ✔ workspace configure
√ Executing: "C:\tizen-studio\tools\emulator\bin\em-cli.bat" list-vm
√ Executing: "C:\tizen-studio\tools\sdb.exe" devices
√ Executing: "C:\tizen-studio\tools\emulator\bin\em-cli.bat" detail -n T-samsung-7.0-x86
√ Executing: "C:\tizen-studio\tools\emulator\bin\em-cli.bat" detail -n W-6.5-circle-x86
task: ✔ target list
┌─────────────────────────────────────────────────────────────────┐
│ ✔ SUMMARY | 14/08/2024, 11:31:32 | rnv@                         │
│ $ rnv target list -p tizen                                      │
├─────────────────────────────────────────────────────────────────┤
│ Project: @rnv/template-starter@1.0.0                            │
│ Workspace: rnv                                                  │
│ Platform (-p): tizen                                            │
│ Engine: @rnv/engine-rn-web                                      │
│ App Config (-c): template                                       │
│ Build Scheme (-s): debug                                        │
│ Supported Platforms: ios, android, androidtv, firetv, androidwear, web, tizen, tvos, webos, macos, tizenwatch, kaios, chromecast, linux, windows
│ Env Info: win32 | x64 | node v18.20.3                           │
│ Executed Time: 0h:0m:6s:791ms                                   │
│
Tizen Targets:

│ You are trying to run global rnv command in your current project.
│ This might lead to unexpected behaviour.
│ Run your rnv command with npx prefix:
│ npx rnv target list -p tizen
└─────────────────────────────────────────────────────────────────┘

C:\Users\dev\Desktop\renative\packages\template-starter>
```

```
>C:\tizen-studio\tools\emulator\bin\em-cli.bat list-vm
T-samsung-7.0-x86
W-6.5-circle-x86
```

**Comment by Marius456** [comment]
> doesn't show any targets on windows
> 
> ```
> C:\Users\dev\Desktop\renative\packages\template-starter>npx rnv target list -p tizen
> 
> ┌─────────────────────────────────────────────────────────────────┐
> │ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
> │ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
> │ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
> │ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
> │ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
> │ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
> │ $ rnv target list -p tizen                                      │
> └─────────────────────────────────────────────────────────────────┘
> info: Current platform: tizen
> info: Current engine: @rnv/engine-rn-web (C:\Users\dev\Desktop\renative\packages\template-starter\node_modules\@rnv\engine-rn-web)
> task: ○ target list ↺1
> task: ○ workspace configure ↺1
> task: ✔ workspace configure
> √ Executing: "C:\tizen-studio\tools\emulator\bin\em-cli.bat" list-vm
> √ Executing: "C:\tizen-studio\tools\sdb.exe" devices
> √ Executing: "C:\tizen-studio\tools\emulator\bin\em-cli.bat" detail -n T-samsung-7.0-x86
> √ Executing: "C:\tizen-studio\tools\emulator\bin\em-cli.bat" detail -n W-6.5-circle-x86
> task: ✔ target list
> ┌─────────────────────────────────────────────────────────────────┐
> │ ✔ SUMMARY | 14/08/2024, 11:31:32 | rnv@                         │
> │ $ rnv target list -p tizen                                      │
> ├─────────────────────────────────────────────────────────────────┤
> │ Project: @rnv/template-starter@1.0.0                            │
> │ Workspace: rnv                                                  │
> │ Platform (-p): tizen                                            │
> │ Engine: @rnv/engine-rn-web                                      │
> │ App Config (-c): template                                       │
> │ Build Scheme (-s): debug                                        │
> │ Supported Platforms: ios, android, androidtv, firetv, androidwear, web, tizen, tvos, webos, macos, tizenwatch, kaios, chromecast, linux, windows
> │ Env Info: win32 | x64 | node v18.20.3                           │
> │ Executed Time: 0h:0m:6s:791ms                                   │
> │
> Tizen Targets:
> 
> │ You are trying to run global rnv command in your current project.
> │ This might lead to unexpected behaviour.
> │ Run your rnv command with npx prefix:
> │ npx rnv target list -p tizen
> └─────────────────────────────────────────────────────────────────┘
> 
> C:\Users\dev\Desktop\renative\packages\template-starter>
> ```
> 
> ```
> >C:\tizen-studio\tools\emulator\bin\em-cli.bat list-vm
> T-samsung-7.0-x86
> W-6.5-circle-x86
> ```

works for me in windows 11
`PS D:\Projects\renative\packages\template-starter> npx rnv target list -p tizen     

┌─────────────────────────────────────────────────────────────────┐
│ ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗ │
│ ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝ │
│ ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗   │
│ ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝   │
│ ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗ │
│ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝ │
│ $ rnv target list -p tizen                                      │
└─────────────────────────────────────────────────────────────────┘
info: Current platform: tizen
info: Current engine: @rnv/engine-rn-web (D:\Projects\renative\packages\template-starter\node_modules\@rnv\engine-rn-web)
task: ○ target list ↺1
task: ○ workspace configure ↺1
task: ✔ workspace configure
✔ Executing: "D:\Programs\tizen\tizen-studio\tools\emulator\bin\em-cli.bat" list-vm
✔ Executing: "D:\Programs\tizen\tizen-studio\tools\sdb.exe" devices
✔ Executing: "D:\Programs\tizen\tizen-studio\tools\emulator\bin\em-cli.bat" detail -n M-7.0-x86
✔ Executing: "D:\Programs\tizen\tizen-studio\tools\emulator\bin\em-cli.bat" detail -n T-8.0-x86
✔ Executing: "D:\Programs\tizen\tizen-studio\tools\emulator\bin\em-cli.bat" detail -n W-7.0-circle-x86
task: ✔ target list
┌─────────────────────────────────────────────────────────────────┐
│ ✔ SUMMARY | 8/14/2024, 11:44:24 AM | rnv@                       │
│ $ rnv target list -p tizen                                      │
├─────────────────────────────────────────────────────────────────┤
│ Project: @rnv/template-starter@1.0.0                            │
│ Workspace: rnv                                                  │
│ Platform (-p): tizen                                            │
│ Engine: @rnv/engine-rn-web                                      │
│ App Config (-c): template                                       │
│ Build Scheme (-s): debug                                        │
│ Supported Platforms: ios, android, androidtv, firetv, androidwear, web, tizen, tvos, webos, macos, tizenwatch, kaios, chromecast, linux, windows
│ Env Info: win32 | x64 | node v18.18.1                           │
│ Executed Time: 0h:0m:5s:677ms                                   │
│
Tizen Targets:
[0]> T-8.0-x86

│ You are trying to run global rnv command in your current project.
│ This might lead to unexpected behaviour.
│ Run your rnv command with npx prefix:
│ npx rnv target list -p tizen
└─────────────────────────────────────────────────────────────────┘
PS D:\Projects\renative\packages\template-starter> D:\Programs\tizen\tizen-studio\tools\emulator\bin\em-cli.bat list-vm
M-7.0-x86
T-8.0-x86
W-7.0-circle-x86
PS D:\Projects\renative\packages\template-starter> 

`

**Comment by pauliusguzas** [comment]
Works on simulators as expected, devices show up on all commands

**Review by pauliusguzas — APPROVED** [review]

**Comment by pauliusguzas** [comment]
remaining issue moved to https://github.com/flexn-io/renative/issues/1666

**Pull request merged**
